/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#ffaba8',
        'on-surface': '#53251b',
        'on-surface-variant': '#885044',
        primary: '#9d4241',
        'surface-bright': '#fff8f6',
        'surface-container': '#ffe9e5',
        'surface-container-high': '#ffe2dc',
        'surface-container-highest': '#ffdad3',
        'surface-container-low': '#fff0ee',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#ffcfc5',
        'on-primary': '#fff7f6',
        'on-primary-container': '#702022',
        'inverse-primary': '#f88885',
        'primary-fixed': '#ffaba8',
        'primary-fixed-dim': '#ff9693',
        surface: '#fff8f6',
        background: '#fff8f6',
        secondary: '#3c6572',
        tertiary: '#2c6771',
        outline: '#a86b5e',
        'outline-variant': '#e7a192',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '48px',
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Montserrat', 'sans-serif'],
        label: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
