/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:                '#131313',
        surface:                   '#1E2020',
        'surface-high':            '#282A2B',
        'surface-container':       '#1E2020',
        'surface-container-high':  '#282A2B',
        'surface-container-highest':'#353739',
        'surface-container-low':   '#181A1B',
        'surface-container-lowest':'#131313',
        'surface-dim':             '#0F1010',
        'surface-bright':          '#282A2B',
        primary:                   '#00FFA3',
        'on-primary':              '#004D30',
        'primary-container':       'rgba(0,255,163,0.12)',
        'on-primary-container':    '#00FFA3',
        'inverse-primary':         '#004D30',
        'primary-fixed':           '#00FFA3',
        'primary-fixed-dim':       '#00CC82',
        'primary-glow':            '#ECB2FF',
        'cyber-purple':            '#BD00FF',
        secondary:                 '#BD00FF',
        tertiary:                  '#ECB2FF',
        'on-surface':              '#E2E2E2',
        'on-surface-variant':      '#888888',
        'on-surface-dim':          '#888888',
        outline:                   '#514255',
        'outline-variant':         '#2E3032',
        'acid-green':              '#00FFA3',
        'acid-green-txt':          '#004D30',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1.25rem',
        xl: '2rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '20px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '48px',
      },
      fontFamily: {
        display: ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body:    ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label:   ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans:    ['Montserrat', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['48px', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg':        ['32px', { lineHeight: '1.15', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '1.2',  fontWeight: '700' }],
        'headline-md':        ['22px', { lineHeight: '1.3',  fontWeight: '700' }],
        'body-lg':            ['18px', { lineHeight: '1.6',  fontWeight: '500' }],
        'body-md':            ['15px', { lineHeight: '1.5',  fontWeight: '400' }],
        'label-md':           ['13px', { lineHeight: '1.2',  letterSpacing: '0.04em', fontWeight: '600' }],
        caption:              ['11px', { lineHeight: '1.4',  fontWeight: '500' }],
      },
      boxShadow: {
        'neon-green':  '0 0 20px rgba(0,255,163,0.4)',
        'neon-purple': '0 0 20px rgba(189,0,255,0.4)',
        card:          '0 4px 24px rgba(0,0,0,0.5)',
      },
    },
  },
  plugins: [],
}
